#include "Base_Model_three_drones_macros.h"
/*
 * Copyright 2026 The MathWorks, Inc.
 *
 * File    : Base_Model_three_drones_fmu.c
 *
 * Abstract:
 *      FMI target wrapper generated by Simulink.
 *
 */

/*==================*
 * Required defines *
 *==================*/

#ifndef MODEL
# error Must specify a model name.  Define MODEL=name.
#else
/* create generic macros that work with any model */
# define EXPAND_CONCAT(name1,name2) name1 ## name2
# define CONCAT(name1,name2) EXPAND_CONCAT(name1,name2)
# define MODEL_INITIALIZE CONCAT(MODEL,_initialize)
# define MODEL_STEP       CONCAT(MODEL,_step)
# define MODEL_TERMINATE  CONCAT(MODEL,_terminate)
# define RT_MDL_TYPE      RT_MODEL_Base_Model_three_drones_T
#endif
#define QUOTE1(name) #name
#define QUOTE(name) QUOTE1(name)    /* need to expand name    */
#if defined(__MINGW32__) && defined(__GNUC__) && defined(__cplusplus)
#define __STDC_FORMAT_MACROS 1
#endif
/*==========*
 * Includes *
 *==========*/
#include <math.h>
#include <time.h>
#include <stdio.h>   /* optional for printf */
#include <string.h>  /* optional for strcmp */
#include "rtmodel.h" /* optional for automated builds */
#include "Base_Model_three_drones.h"
#include "Base_Model_three_drones_private.h"
#include "fmi2Functions.h"
#include "RTWCG_FMU_util.h"

/*====================*
 * External functions *
 *====================*/
extern void MODEL_INITIALIZE();
extern void MODEL_TERMINATE();
extern void MODEL_STEP();
/*==================================*
 * Global data local to this module *
 *==================================*/
const char *RT_MEMORY_ALLOCATION_ERROR = "memory allocation error"; 
typedef struct {
    /* Model data */
    RT_MDL_TYPE *S;
    fmi2EventInfo eventInfo;
    /* FMU data*/
    fmi2String instanceName;
    fmi2Type type;
    fmi2String GUID;
    fmi2String resourceLocation;
    const fmi2CallbackFunctions *functions;
    fmi2Boolean visible;
    fmi2Boolean loggingOn;
    fmi2Boolean initialized;
    fmi2Real time;
    /* Variable Indices */
    real_T **rList;
    real_T *rBuffer;
    int32_T **iList;
    int32_T *iBuffer;
    boolean_T **bList;
    char **sList;
    int32_T *sSize;
    /* Output Buffers */
    real_T *rOutput;
    int32_T *iOutput;
    boolean_T *bOutput;
    char **sOutput;
} FMUModelData;
FMUModelData *_instance = NULL;
typedef struct {
    ExtU_Base_Model_three_drones_T ExternalInput;
    ExtY_Base_Model_three_drones_T ExternalOutput;
    P_Base_Model_three_drones_T Parameter;
    DW_Base_Model_three_drones_T dWork;
    real_T rListBuffer[86];
    fmi2Real time;
    boolean_T isNullInstance;
} FMUInternalState;
 ;
void fmu_syncToBuffer(void) {
}
 
void fmu_syncFromBuffer(void) {
}
void fmu_LogOutput(void) {
    FMUModelData *modelData = (FMUModelData *)_instance;
    modelData->rOutput[0] = *(modelData->rList[18]);
    modelData->rOutput[1] = *(modelData->rList[19]);
    modelData->rOutput[2] = *(modelData->rList[20]);
    modelData->rOutput[3] = *(modelData->rList[21]);
    modelData->rOutput[4] = *(modelData->rList[22]);
    modelData->rOutput[5] = *(modelData->rList[23]);
    modelData->rOutput[6] = *(modelData->rList[24]);
    modelData->rOutput[7] = *(modelData->rList[25]);
    modelData->rOutput[8] = *(modelData->rList[26]);
    modelData->rOutput[9] = *(modelData->rList[27]);
    modelData->rOutput[10] = *(modelData->rList[28]);
    modelData->rOutput[11] = *(modelData->rList[29]);
    modelData->rOutput[12] = *(modelData->rList[30]);
    modelData->rOutput[13] = *(modelData->rList[31]);
    modelData->rOutput[14] = *(modelData->rList[32]);
    modelData->rOutput[15] = *(modelData->rList[33]);
    modelData->rOutput[16] = *(modelData->rList[34]);
    modelData->rOutput[17] = *(modelData->rList[35]);
    modelData->rOutput[18] = *(modelData->rList[36]);
    modelData->rOutput[19] = *(modelData->rList[37]);
    modelData->rOutput[20] = *(modelData->rList[38]);
    modelData->rOutput[21] = *(modelData->rList[39]);
    modelData->rOutput[22] = *(modelData->rList[40]);
    modelData->rOutput[23] = *(modelData->rList[41]);
    modelData->rOutput[24] = *(modelData->rList[42]);
    modelData->rOutput[25] = *(modelData->rList[43]);
    modelData->rOutput[26] = *(modelData->rList[44]);
    modelData->rOutput[27] = *(modelData->rList[45]);
    modelData->rOutput[28] = *(modelData->rList[46]);
    modelData->rOutput[29] = *(modelData->rList[47]);
    modelData->rOutput[30] = *(modelData->rList[48]);
    modelData->rOutput[31] = *(modelData->rList[49]);
    modelData->rOutput[32] = *(modelData->rList[50]);
    modelData->rOutput[33] = *(modelData->rList[51]);
    modelData->rOutput[34] = *(modelData->rList[52]);
    modelData->rOutput[35] = *(modelData->rList[53]);
    modelData->rOutput[36] = *(modelData->rList[54]);
    modelData->rOutput[37] = *(modelData->rList[55]);
    modelData->rOutput[38] = *(modelData->rList[56]);
    modelData->rOutput[39] = *(modelData->rList[57]);
    modelData->rOutput[40] = *(modelData->rList[58]);
    modelData->rOutput[41] = *(modelData->rList[59]);
    modelData->rOutput[42] = *(modelData->rList[60]);
    modelData->rOutput[43] = *(modelData->rList[61]);
    modelData->rOutput[44] = *(modelData->rList[62]);
}
void fmu_RestoreOutput(void) {
    FMUModelData *modelData = (FMUModelData *)_instance;
    *(modelData->rList[18]) = modelData->rOutput[0];
    *(modelData->rList[19]) = modelData->rOutput[1];
    *(modelData->rList[20]) = modelData->rOutput[2];
    *(modelData->rList[21]) = modelData->rOutput[3];
    *(modelData->rList[22]) = modelData->rOutput[4];
    *(modelData->rList[23]) = modelData->rOutput[5];
    *(modelData->rList[24]) = modelData->rOutput[6];
    *(modelData->rList[25]) = modelData->rOutput[7];
    *(modelData->rList[26]) = modelData->rOutput[8];
    *(modelData->rList[27]) = modelData->rOutput[9];
    *(modelData->rList[28]) = modelData->rOutput[10];
    *(modelData->rList[29]) = modelData->rOutput[11];
    *(modelData->rList[30]) = modelData->rOutput[12];
    *(modelData->rList[31]) = modelData->rOutput[13];
    *(modelData->rList[32]) = modelData->rOutput[14];
    *(modelData->rList[33]) = modelData->rOutput[15];
    *(modelData->rList[34]) = modelData->rOutput[16];
    *(modelData->rList[35]) = modelData->rOutput[17];
    *(modelData->rList[36]) = modelData->rOutput[18];
    *(modelData->rList[37]) = modelData->rOutput[19];
    *(modelData->rList[38]) = modelData->rOutput[20];
    *(modelData->rList[39]) = modelData->rOutput[21];
    *(modelData->rList[40]) = modelData->rOutput[22];
    *(modelData->rList[41]) = modelData->rOutput[23];
    *(modelData->rList[42]) = modelData->rOutput[24];
    *(modelData->rList[43]) = modelData->rOutput[25];
    *(modelData->rList[44]) = modelData->rOutput[26];
    *(modelData->rList[45]) = modelData->rOutput[27];
    *(modelData->rList[46]) = modelData->rOutput[28];
    *(modelData->rList[47]) = modelData->rOutput[29];
    *(modelData->rList[48]) = modelData->rOutput[30];
    *(modelData->rList[49]) = modelData->rOutput[31];
    *(modelData->rList[50]) = modelData->rOutput[32];
    *(modelData->rList[51]) = modelData->rOutput[33];
    *(modelData->rList[52]) = modelData->rOutput[34];
    *(modelData->rList[53]) = modelData->rOutput[35];
    *(modelData->rList[54]) = modelData->rOutput[36];
    *(modelData->rList[55]) = modelData->rOutput[37];
    *(modelData->rList[56]) = modelData->rOutput[38];
    *(modelData->rList[57]) = modelData->rOutput[39];
    *(modelData->rList[58]) = modelData->rOutput[40];
    *(modelData->rList[59]) = modelData->rOutput[41];
    *(modelData->rList[60]) = modelData->rOutput[42];
    *(modelData->rList[61]) = modelData->rOutput[43];
    *(modelData->rList[62]) = modelData->rOutput[44];
}
const char* fmu_resourceLocation(void) {
    FMUModelData *modelData = (FMUModelData *)_instance;
    return (const char *)modelData->resourceLocation;
}

const void* fmu_callback(int fmuVersion) {
    FMUModelData *modelData = (FMUModelData *)_instance;
    if(fmuVersion <= 2) {
       return (const void *)modelData->functions;
    }
    else {
       return NULL;
    }
}

int fmu_fmuVisible(void) {
    FMUModelData *modelData = (FMUModelData *)_instance;
    return (int)modelData->visible;
}

int fmu_fmuLogging(void) {
    FMUModelData *modelData = (FMUModelData *)_instance;
    return (int)modelData->loggingOn;
}

char* fmu_instanceName(void) {
    FMUModelData *modelData = (FMUModelData *)_instance;
    return (char*)modelData->instanceName;
}

int fmu_restoreSimScapeInitialState(void) {
    return 0;
}
/*====================*
 *  Static functions  *
 *====================*/
static void rtOneStep(RT_MDL_TYPE *S) {
    (void)S;
    MODEL_STEP();
    fmu_RestoreOutput();
}
/*===============*
 * FMI functions *
 *===============*/

const char* fmi2GetTypesPlatform(void) {
    static char str[] = {'d','e','f','a','u','l','t','\0'};
    return str;
}

const char* fmi2GetVersion(void) {
    static char str[] = {'2','.','0','\0'};
    return str;
}

fmi2Status fmi2SetDebugLogging(fmi2Component c, fmi2Boolean loggingOn, size_t nCategories, const fmi2String categories[]) {  
    FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    (void)nCategories;
    (void)categories;

    modelData->loggingOn = loggingOn;
    return fmi2OK;
}

fmi2Component fmi2Instantiate(fmi2String instanceName, fmi2Type fmuType, fmi2String fmuGUID,
                            fmi2String fmuResourceLocation, const fmi2CallbackFunctions *functions,
                            fmi2Boolean visible, fmi2Boolean loggingOn) {

    FMUModelData *modelData = NULL;
    const char_T *errmsg = NULL;

    if (!functions->logger) {
        return NULL;
    } else if (!instanceName || strlen(instanceName) == 0) {
        functions->logger(functions->componentEnvironment, "?", fmi2Error, "error",
            "fmi2Instantiate: Missing instance name.");
        return NULL;
    } else if (!fmuGUID || strlen(fmuGUID) == 0) {
        functions->logger(functions->componentEnvironment, instanceName, fmi2Error, "error",
            "fmi2Instantiate: Missing GUID.");
        return NULL;
    } else if (strcmp(fmuGUID, "{ecfd1e4c-2ac4-094d-56d6-a8105e08f676}")) {
        functions->logger(functions->componentEnvironment, instanceName, fmi2Error, "error",
            "fmi2Instantiate: Wrong GUID %s. Expected %s.", fmuGUID, "{ecfd1e4c-2ac4-094d-56d6-a8105e08f676}");
        return NULL;
    }
    if (_instance) {
        functions->logger(functions->componentEnvironment, instanceName, fmi2Error, "error",
            "fmi2Instantiate: This FMU cannot support instantiating multiple instances in one process.");
        return NULL;
    }
    _instance = modelData = (FMUModelData*)calloc(1, sizeof(FMUModelData));
    if (!modelData) {
        functions->logger(functions->componentEnvironment, instanceName, fmi2Error, "error",
            "fmi2Instantiate: Memory allocation error.");
        return NULL;
    }
    modelData->S = MODEL(); /* using static */
    if (modelData->S == NULL) {
        functions->logger(functions->componentEnvironment, instanceName, fmi2Error, "error",
            "Memory allocation error during model registration");
        return NULL;
    }
    errmsg = (const char_T *) (rtmGetErrorStatus(modelData->S));
    if (errmsg != NULL) {
        functions->logger(functions->componentEnvironment, instanceName, fmi2Error, "error",
            "Error during model registration: %s\n", errmsg);
        MODEL_TERMINATE();
        return NULL;
    }
    modelData->eventInfo.newDiscreteStatesNeeded = fmi2False;
    modelData->eventInfo.terminateSimulation = fmi2False;
    modelData->eventInfo.nominalsOfContinuousStatesChanged = fmi2False;
    modelData->eventInfo.valuesOfContinuousStatesChanged = fmi2False;
    modelData->eventInfo.nextEventTimeDefined = fmi2False;
    modelData->eventInfo.nextEventTime = 0;
    
    modelData->instanceName = (fmi2String)calloc(strlen(instanceName)+1, sizeof(fmi2Char*));
    if (!modelData->instanceName) {
        functions->logger(functions->componentEnvironment, instanceName, fmi2Error, "error",
            "fmi2Instantiate: Memory allocation error.");
        return NULL;
    }
    strcpy((char *)modelData->instanceName, (char *)instanceName);
    modelData->type = fmuType;
    modelData->GUID = (fmi2String)calloc(strlen(fmuGUID)+1, sizeof(fmi2Char*));
    if (!modelData->GUID) {
        functions->logger(functions->componentEnvironment, instanceName, fmi2Error, "error",
            "fmi2Instantiate: Memory allocation error.");
        return NULL;
    }
    strcpy((char *)modelData->GUID, (char *)fmuGUID);
    if (fmuResourceLocation) {
        modelData->resourceLocation = uriToLocal(fmuResourceLocation);
        if (!modelData->resourceLocation) {
            functions->logger(functions->componentEnvironment, instanceName, fmi2Error, "error",
                "fmi2Instantiate: Memory allocation error.");
            return NULL;
        }
        else if (strlen(modelData->resourceLocation) == 0) {
            functions->logger(functions->componentEnvironment, instanceName, fmi2Error, "error",
                "fmi2Instantiate: uriToLocal cannot handle fmuResourceLocation.");
            return NULL;
        }
    } else {
        modelData->resourceLocation = fmuResourceLocation;
    }
    modelData->functions = functions;
    modelData->visible = visible;
    modelData->loggingOn = loggingOn;
    modelData->initialized = fmi2False;
    modelData->time = 0.0;
    /* initialize variables */
    if (rtmGetStopRequested(modelData->S)) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                fmi2Error, "error", "stop requested in fmi2Instantiate");
        return NULL;
    }
    modelData->rList = (real_T**)calloc(86, sizeof(real_T*));
    if (!modelData->rList) {
        functions->logger(functions->componentEnvironment, instanceName, fmi2Error, "error",
                "fmi2Instantiate: Memory allocation error.");
        return NULL;
    }
    modelData->rOutput = (real_T*)calloc(45, sizeof(real_T));
    if (!modelData->rOutput) {
        functions->logger(functions->componentEnvironment, instanceName, fmi2Error, "error",
                "fmi2Instantiate: Memory allocation error.");
        return NULL;
    }
    modelData->rList[0] = &(Base_Model_three_drones_U.Desired_Cable_Forces[0]);
    modelData->rList[1] = &(Base_Model_three_drones_U.Desired_Cable_Forces[1]);
    modelData->rList[2] = &(Base_Model_three_drones_U.Desired_Cable_Forces[2]);
    modelData->rList[3] = &(Base_Model_three_drones_U.Desired_Cable_Forces[3]);
    modelData->rList[4] = &(Base_Model_three_drones_U.Desired_Cable_Forces[4]);
    modelData->rList[5] = &(Base_Model_three_drones_U.Desired_Cable_Forces[5]);
    modelData->rList[6] = &(Base_Model_three_drones_U.Desired_Cable_Forces[6]);
    modelData->rList[7] = &(Base_Model_three_drones_U.Desired_Cable_Forces[7]);
    modelData->rList[8] = &(Base_Model_three_drones_U.Desired_Cable_Forces[8]);
    modelData->rList[9] = &(Base_Model_three_drones_U.Desired_Cable_Forces_Derivatives[0]);
    modelData->rList[10] = &(Base_Model_three_drones_U.Desired_Cable_Forces_Derivatives[1]);
    modelData->rList[11] = &(Base_Model_three_drones_U.Desired_Cable_Forces_Derivatives[2]);
    modelData->rList[12] = &(Base_Model_three_drones_U.Desired_Cable_Forces_Derivatives[3]);
    modelData->rList[13] = &(Base_Model_three_drones_U.Desired_Cable_Forces_Derivatives[4]);
    modelData->rList[14] = &(Base_Model_three_drones_U.Desired_Cable_Forces_Derivatives[5]);
    modelData->rList[15] = &(Base_Model_three_drones_U.Desired_Cable_Forces_Derivatives[6]);
    modelData->rList[16] = &(Base_Model_three_drones_U.Desired_Cable_Forces_Derivatives[7]);
    modelData->rList[17] = &(Base_Model_three_drones_U.Desired_Cable_Forces_Derivatives[8]);
    modelData->rList[18] = &(Base_Model_three_drones_Y.Load_Position[0]);
    modelData->rList[19] = &(Base_Model_three_drones_Y.Load_Position[1]);
    modelData->rList[20] = &(Base_Model_three_drones_Y.Load_Position[2]);
    modelData->rList[21] = &(Base_Model_three_drones_Y.Load_LinVelocity[0]);
    modelData->rList[22] = &(Base_Model_three_drones_Y.Load_LinVelocity[1]);
    modelData->rList[23] = &(Base_Model_three_drones_Y.Load_LinVelocity[2]);
    modelData->rList[24] = &(Base_Model_three_drones_Y.Load_Orientation[0]);
    modelData->rList[25] = &(Base_Model_three_drones_Y.Load_Orientation[3]);
    modelData->rList[26] = &(Base_Model_three_drones_Y.Load_Orientation[6]);
    modelData->rList[27] = &(Base_Model_three_drones_Y.Load_Orientation[1]);
    modelData->rList[28] = &(Base_Model_three_drones_Y.Load_Orientation[4]);
    modelData->rList[29] = &(Base_Model_three_drones_Y.Load_Orientation[7]);
    modelData->rList[30] = &(Base_Model_three_drones_Y.Load_Orientation[2]);
    modelData->rList[31] = &(Base_Model_three_drones_Y.Load_Orientation[5]);
    modelData->rList[32] = &(Base_Model_three_drones_Y.Load_Orientation[8]);
    modelData->rList[33] = &(Base_Model_three_drones_Y.Load_Orientation_Derivative[0]);
    modelData->rList[34] = &(Base_Model_three_drones_Y.Load_Orientation_Derivative[3]);
    modelData->rList[35] = &(Base_Model_three_drones_Y.Load_Orientation_Derivative[6]);
    modelData->rList[36] = &(Base_Model_three_drones_Y.Load_Orientation_Derivative[1]);
    modelData->rList[37] = &(Base_Model_three_drones_Y.Load_Orientation_Derivative[4]);
    modelData->rList[38] = &(Base_Model_three_drones_Y.Load_Orientation_Derivative[7]);
    modelData->rList[39] = &(Base_Model_three_drones_Y.Load_Orientation_Derivative[2]);
    modelData->rList[40] = &(Base_Model_three_drones_Y.Load_Orientation_Derivative[5]);
    modelData->rList[41] = &(Base_Model_three_drones_Y.Load_Orientation_Derivative[8]);
    modelData->rList[42] = &(Base_Model_three_drones_Y.Load_AngVelocity[0]);
    modelData->rList[43] = &(Base_Model_three_drones_Y.Load_AngVelocity[1]);
    modelData->rList[44] = &(Base_Model_three_drones_Y.Load_AngVelocity[2]);
    modelData->rList[45] = &(Base_Model_three_drones_Y.Drone_Positions[0]);
    modelData->rList[46] = &(Base_Model_three_drones_Y.Drone_Positions[1]);
    modelData->rList[47] = &(Base_Model_three_drones_Y.Drone_Positions[2]);
    modelData->rList[48] = &(Base_Model_three_drones_Y.Drone_Positions[3]);
    modelData->rList[49] = &(Base_Model_three_drones_Y.Drone_Positions[4]);
    modelData->rList[50] = &(Base_Model_three_drones_Y.Drone_Positions[5]);
    modelData->rList[51] = &(Base_Model_three_drones_Y.Drone_Positions[6]);
    modelData->rList[52] = &(Base_Model_three_drones_Y.Drone_Positions[7]);
    modelData->rList[53] = &(Base_Model_three_drones_Y.Drone_Positions[8]);
    modelData->rList[54] = &(Base_Model_three_drones_Y.Drones_LinVelocity[0]);
    modelData->rList[55] = &(Base_Model_three_drones_Y.Drones_LinVelocity[1]);
    modelData->rList[56] = &(Base_Model_three_drones_Y.Drones_LinVelocity[2]);
    modelData->rList[57] = &(Base_Model_three_drones_Y.Drones_LinVelocity[3]);
    modelData->rList[58] = &(Base_Model_three_drones_Y.Drones_LinVelocity[4]);
    modelData->rList[59] = &(Base_Model_three_drones_Y.Drones_LinVelocity[5]);
    modelData->rList[60] = &(Base_Model_three_drones_Y.Drones_LinVelocity[6]);
    modelData->rList[61] = &(Base_Model_three_drones_Y.Drones_LinVelocity[7]);
    modelData->rList[62] = &(Base_Model_three_drones_Y.Drones_LinVelocity[8]);
    modelData->rList[63] = &(modelData->time);
    modelData->rList[64] = &(Attachment_Point_Vectors[0]);
    modelData->rList[65] = &(Attachment_Point_Vectors[1]);
    modelData->rList[66] = &(Attachment_Point_Vectors[2]);
    modelData->rList[67] = &(Attachment_Point_Vectors[3]);
    modelData->rList[68] = &(Attachment_Point_Vectors[4]);
    modelData->rList[69] = &(Attachment_Point_Vectors[5]);
    modelData->rList[70] = &(Attachment_Point_Vectors[6]);
    modelData->rList[71] = &(Attachment_Point_Vectors[7]);
    modelData->rList[72] = &(Attachment_Point_Vectors[8]);
    modelData->rList[73] = &(Cable_Resting_Length);
    modelData->rList[74] = &(Load_Damping_Coef);
    modelData->rList[75] = &(Load_Inertia_Matrix[0]);
    modelData->rList[76] = &(Load_Inertia_Matrix[1]);
    modelData->rList[77] = &(Load_Inertia_Matrix[2]);
    modelData->rList[78] = &(Load_Inertia_Matrix[3]);
    modelData->rList[79] = &(Load_Inertia_Matrix[4]);
    modelData->rList[80] = &(Load_Inertia_Matrix[5]);
    modelData->rList[81] = &(Load_Inertia_Matrix[6]);
    modelData->rList[82] = &(Load_Inertia_Matrix[7]);
    modelData->rList[83] = &(Load_Inertia_Matrix[8]);
    modelData->rList[84] = &(Load_Mass);
    modelData->rList[85] = &(g);
    fmu_syncToBuffer();

    return modelData;
}

void fmi2FreeInstance(fmi2Component c) {
    FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    const char_T *errStatus = NULL;
    
    if (!modelData) return;
    errStatus = (const char_T *) (rtmGetErrorStatus(modelData->S));
    
    if (errStatus != NULL && strcmp(errStatus, "Simulation finished")) {
        modelData->functions->logger(modelData->functions->componentEnvironment, 
                modelData->instanceName, fmi2Error, "error", "%s", errStatus);

        MODEL_TERMINATE();
        return;
    }    
    MODEL_TERMINATE();
    
    free((void*)modelData->instanceName);
    free((void*)modelData->GUID);
    free((void*)modelData->resourceLocation);
    free((void*)modelData->rList);
    free((void*)modelData->rOutput);
    free((void*)modelData);
    _instance = NULL;
}

fmi2Status fmi2SetupExperiment(fmi2Component c, fmi2Boolean toleranceDefined, fmi2Real tolerance,
                            fmi2Real startTime, fmi2Boolean stopTimeDefined, fmi2Real stopTime) {

    FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    (void)toleranceDefined;
    (void)tolerance;
    (void)stopTimeDefined;
    (void)stopTime;

    if (fabs(startTime) > 1.0E-7) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                fmi2Error, "error", "start time is not zero.");
        return fmi2Error;
    }

    modelData->time = startTime;
    return fmi2OK;
}

fmi2Status fmi2EnterInitializationMode(fmi2Component c) {
   FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    MODEL_INITIALIZE();
    modelData->initialized = fmi2True;
    return fmi2OK;
}

fmi2Status fmi2ExitInitializationMode(fmi2Component c) {
    FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    /* call step after setting input variables*/
    rtOneStep(modelData->S);;
    if (rtmGetStopRequested(modelData->S)) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                fmi2Error, "error", "stop requested in fmi2ExitInitializationMode");
        return fmi2Error;
    }
    return fmi2OK;
}

fmi2Status fmi2Terminate(fmi2Component c) {
    (void)c;
    return fmi2OK;
}

fmi2Status fmi2Reset(fmi2Component c) {
    FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    const char_T *errmsg = (const char_T *) (rtmGetErrorStatus(modelData->S));
    /* Reset model data */
    if (errmsg != NULL && strcmp(errmsg, "Simulation finished")) {
        modelData->functions->logger(modelData->functions->componentEnvironment, 
                modelData->instanceName, fmi2Error, "error", "%s", errmsg);

        MODEL_TERMINATE();
        return fmi2Error;
    }    
    MODEL_TERMINATE();
    
    modelData->S = MODEL(); /* using static */
    if (modelData->S == NULL) {
        modelData->functions->logger(modelData->functions->componentEnvironment, 
               modelData->instanceName, fmi2Error, "error",
               "Memory allocation error during model registration");
        return fmi2Error;
    }
    errmsg = (const char_T *) (rtmGetErrorStatus(modelData->S));
    if (errmsg != NULL) {
        modelData->functions->logger(modelData->functions->componentEnvironment, 
                modelData->instanceName, fmi2Error, "error",
                "Error during model registration: %s\n", errmsg);
        MODEL_TERMINATE();
        return fmi2Error;
    }
    modelData->eventInfo.newDiscreteStatesNeeded = fmi2False;
    modelData->eventInfo.terminateSimulation = fmi2False;
    modelData->eventInfo.nominalsOfContinuousStatesChanged = fmi2False;
    modelData->eventInfo.valuesOfContinuousStatesChanged = fmi2False;
    modelData->eventInfo.nextEventTimeDefined = fmi2False;
    modelData->eventInfo.nextEventTime = 0;
    modelData->rList[0] = &(Base_Model_three_drones_U.Desired_Cable_Forces[0]);
    modelData->rList[1] = &(Base_Model_three_drones_U.Desired_Cable_Forces[1]);
    modelData->rList[2] = &(Base_Model_three_drones_U.Desired_Cable_Forces[2]);
    modelData->rList[3] = &(Base_Model_three_drones_U.Desired_Cable_Forces[3]);
    modelData->rList[4] = &(Base_Model_three_drones_U.Desired_Cable_Forces[4]);
    modelData->rList[5] = &(Base_Model_three_drones_U.Desired_Cable_Forces[5]);
    modelData->rList[6] = &(Base_Model_three_drones_U.Desired_Cable_Forces[6]);
    modelData->rList[7] = &(Base_Model_three_drones_U.Desired_Cable_Forces[7]);
    modelData->rList[8] = &(Base_Model_three_drones_U.Desired_Cable_Forces[8]);
    modelData->rList[9] = &(Base_Model_three_drones_U.Desired_Cable_Forces_Derivatives[0]);
    modelData->rList[10] = &(Base_Model_three_drones_U.Desired_Cable_Forces_Derivatives[1]);
    modelData->rList[11] = &(Base_Model_three_drones_U.Desired_Cable_Forces_Derivatives[2]);
    modelData->rList[12] = &(Base_Model_three_drones_U.Desired_Cable_Forces_Derivatives[3]);
    modelData->rList[13] = &(Base_Model_three_drones_U.Desired_Cable_Forces_Derivatives[4]);
    modelData->rList[14] = &(Base_Model_three_drones_U.Desired_Cable_Forces_Derivatives[5]);
    modelData->rList[15] = &(Base_Model_three_drones_U.Desired_Cable_Forces_Derivatives[6]);
    modelData->rList[16] = &(Base_Model_three_drones_U.Desired_Cable_Forces_Derivatives[7]);
    modelData->rList[17] = &(Base_Model_three_drones_U.Desired_Cable_Forces_Derivatives[8]);
    modelData->rList[18] = &(Base_Model_three_drones_Y.Load_Position[0]);
    modelData->rList[19] = &(Base_Model_three_drones_Y.Load_Position[1]);
    modelData->rList[20] = &(Base_Model_three_drones_Y.Load_Position[2]);
    modelData->rList[21] = &(Base_Model_three_drones_Y.Load_LinVelocity[0]);
    modelData->rList[22] = &(Base_Model_three_drones_Y.Load_LinVelocity[1]);
    modelData->rList[23] = &(Base_Model_three_drones_Y.Load_LinVelocity[2]);
    modelData->rList[24] = &(Base_Model_three_drones_Y.Load_Orientation[0]);
    modelData->rList[25] = &(Base_Model_three_drones_Y.Load_Orientation[3]);
    modelData->rList[26] = &(Base_Model_three_drones_Y.Load_Orientation[6]);
    modelData->rList[27] = &(Base_Model_three_drones_Y.Load_Orientation[1]);
    modelData->rList[28] = &(Base_Model_three_drones_Y.Load_Orientation[4]);
    modelData->rList[29] = &(Base_Model_three_drones_Y.Load_Orientation[7]);
    modelData->rList[30] = &(Base_Model_three_drones_Y.Load_Orientation[2]);
    modelData->rList[31] = &(Base_Model_three_drones_Y.Load_Orientation[5]);
    modelData->rList[32] = &(Base_Model_three_drones_Y.Load_Orientation[8]);
    modelData->rList[33] = &(Base_Model_three_drones_Y.Load_Orientation_Derivative[0]);
    modelData->rList[34] = &(Base_Model_three_drones_Y.Load_Orientation_Derivative[3]);
    modelData->rList[35] = &(Base_Model_three_drones_Y.Load_Orientation_Derivative[6]);
    modelData->rList[36] = &(Base_Model_three_drones_Y.Load_Orientation_Derivative[1]);
    modelData->rList[37] = &(Base_Model_three_drones_Y.Load_Orientation_Derivative[4]);
    modelData->rList[38] = &(Base_Model_three_drones_Y.Load_Orientation_Derivative[7]);
    modelData->rList[39] = &(Base_Model_three_drones_Y.Load_Orientation_Derivative[2]);
    modelData->rList[40] = &(Base_Model_three_drones_Y.Load_Orientation_Derivative[5]);
    modelData->rList[41] = &(Base_Model_three_drones_Y.Load_Orientation_Derivative[8]);
    modelData->rList[42] = &(Base_Model_three_drones_Y.Load_AngVelocity[0]);
    modelData->rList[43] = &(Base_Model_three_drones_Y.Load_AngVelocity[1]);
    modelData->rList[44] = &(Base_Model_three_drones_Y.Load_AngVelocity[2]);
    modelData->rList[45] = &(Base_Model_three_drones_Y.Drone_Positions[0]);
    modelData->rList[46] = &(Base_Model_three_drones_Y.Drone_Positions[1]);
    modelData->rList[47] = &(Base_Model_three_drones_Y.Drone_Positions[2]);
    modelData->rList[48] = &(Base_Model_three_drones_Y.Drone_Positions[3]);
    modelData->rList[49] = &(Base_Model_three_drones_Y.Drone_Positions[4]);
    modelData->rList[50] = &(Base_Model_three_drones_Y.Drone_Positions[5]);
    modelData->rList[51] = &(Base_Model_three_drones_Y.Drone_Positions[6]);
    modelData->rList[52] = &(Base_Model_three_drones_Y.Drone_Positions[7]);
    modelData->rList[53] = &(Base_Model_three_drones_Y.Drone_Positions[8]);
    modelData->rList[54] = &(Base_Model_three_drones_Y.Drones_LinVelocity[0]);
    modelData->rList[55] = &(Base_Model_three_drones_Y.Drones_LinVelocity[1]);
    modelData->rList[56] = &(Base_Model_three_drones_Y.Drones_LinVelocity[2]);
    modelData->rList[57] = &(Base_Model_three_drones_Y.Drones_LinVelocity[3]);
    modelData->rList[58] = &(Base_Model_three_drones_Y.Drones_LinVelocity[4]);
    modelData->rList[59] = &(Base_Model_three_drones_Y.Drones_LinVelocity[5]);
    modelData->rList[60] = &(Base_Model_three_drones_Y.Drones_LinVelocity[6]);
    modelData->rList[61] = &(Base_Model_three_drones_Y.Drones_LinVelocity[7]);
    modelData->rList[62] = &(Base_Model_three_drones_Y.Drones_LinVelocity[8]);
    modelData->rList[63] = &(modelData->time);
    modelData->rList[64] = &(Attachment_Point_Vectors[0]);
    modelData->rList[65] = &(Attachment_Point_Vectors[1]);
    modelData->rList[66] = &(Attachment_Point_Vectors[2]);
    modelData->rList[67] = &(Attachment_Point_Vectors[3]);
    modelData->rList[68] = &(Attachment_Point_Vectors[4]);
    modelData->rList[69] = &(Attachment_Point_Vectors[5]);
    modelData->rList[70] = &(Attachment_Point_Vectors[6]);
    modelData->rList[71] = &(Attachment_Point_Vectors[7]);
    modelData->rList[72] = &(Attachment_Point_Vectors[8]);
    modelData->rList[73] = &(Cable_Resting_Length);
    modelData->rList[74] = &(Load_Damping_Coef);
    modelData->rList[75] = &(Load_Inertia_Matrix[0]);
    modelData->rList[76] = &(Load_Inertia_Matrix[1]);
    modelData->rList[77] = &(Load_Inertia_Matrix[2]);
    modelData->rList[78] = &(Load_Inertia_Matrix[3]);
    modelData->rList[79] = &(Load_Inertia_Matrix[4]);
    modelData->rList[80] = &(Load_Inertia_Matrix[5]);
    modelData->rList[81] = &(Load_Inertia_Matrix[6]);
    modelData->rList[82] = &(Load_Inertia_Matrix[7]);
    modelData->rList[83] = &(Load_Inertia_Matrix[8]);
    modelData->rList[84] = &(Load_Mass);
    modelData->rList[85] = &(g);
    fmu_syncToBuffer();
    if (rtmGetStopRequested(modelData->S)) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                fmi2Error, "error", "stop requested in fmi2Reset");
        return fmi2Error;
    }
    return fmi2OK;
}

fmi2Status fmi2GetReal (fmi2Component c, const fmi2ValueReference vr[], size_t nvr, fmi2Real value[]) {
    FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    size_t i;
    if (nvr != 0 && (!value || !vr)) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                    fmi2Error, "error", "invalid memory access");
        return fmi2Error;
    }
    fmu_syncToBuffer();
    for (i = 0; i < nvr; i++) {
        if (vr[i] >= 86.0) {
            modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                    fmi2Error, "error", "valueReference out of range");
            return fmi2Error;
        }
    }
    for (i = 0; i < nvr; i++) {
        value[i] = (fmi2Real)(*modelData->rList[vr[i]]);
        if (modelData->loggingOn) {
            modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
               fmi2OK, "info", "getReal vr:%d, value:%lf", vr[i], value[i]);
        }
    }
    return fmi2OK;
}

fmi2Status fmi2SetReal (fmi2Component c, const fmi2ValueReference vr[], size_t nvr, const fmi2Real value[]) {
    FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    size_t i;
    fmi2Boolean is_diff_value = fmi2False;
    if (nvr != 0 && (!value || !vr)) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                    fmi2Error, "error", "invalid memory access");
        return fmi2Error;
    }
    for (i = 0; i < nvr; i++) {
        if (vr[i] >= 86.0) {
            modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                    fmi2Error, "error", "valueReference out of range");
            return fmi2Error;
        }
    }
    for (i = 0; i < nvr; i++) {
        if (*modelData->rList[vr[i]] != (real_T)(value[i])) {
            is_diff_value = fmi2True;
            *modelData->rList[vr[i]] = (real_T)(value[i]);
        }
        if (modelData->loggingOn) {
            modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
               fmi2OK, "info", "setReal vr:%d, value:%lf", vr[i], value[i]);
        }
    }
    fmu_syncFromBuffer();
    return fmi2OK;
}

fmi2Status fmi2GetInteger(fmi2Component c, const fmi2ValueReference vr[], size_t nvr, fmi2Integer value[]) {
    FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    size_t i;    
    if (nvr != 0 && (!value || !vr)) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                    fmi2Error, "error", "invalid memory access");
        return fmi2Error;
    }
    fmu_syncToBuffer();
    for (i = 0; i < nvr; i++) {
        if (vr[i] >= 0.0) {
            modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                    fmi2Error, "error", "valueReference out of range");
            return fmi2Error;
        }
    }
    for (i = 0; i < nvr; i++) {
        value[i] = (fmi2Integer)(*modelData->iList[vr[i]]);
        if (modelData->loggingOn) {
            modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
               fmi2OK, "info", "getInteger vr:%d, value:%d", vr[i], value[i]);
        }
    }
    return fmi2OK;
}

fmi2Status fmi2SetInteger(fmi2Component c, const fmi2ValueReference vr[], size_t nvr, const fmi2Integer value[]) {
    FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    size_t i;    
    fmi2Boolean is_diff_value = fmi2False;
    if (nvr != 0 && (!value || !vr)) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                    fmi2Error, "error", "invalid memory access");
        return fmi2Error;
    }
    for (i = 0; i < nvr; i++) {
        if (vr[i] >= 0.0) {
            modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                    fmi2Error, "error", "valueReference out of range");
            return fmi2Error;
        }
    }
    for (i = 0; i < nvr; i++) {
        if (*modelData->iList[vr[i]] != (int32_T)(value[i])) {
            is_diff_value = fmi2True;
            *modelData->iList[vr[i]] = (int32_T)(value[i]);
        }
        if (modelData->loggingOn) {
            modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
               fmi2OK, "info", "setInteger vr:%d, value:%d", vr[i], value[i]);
        }
    }
    fmu_syncFromBuffer();
    return fmi2OK;
}

fmi2Status fmi2GetBoolean(fmi2Component c, const fmi2ValueReference vr[], size_t nvr, fmi2Boolean value[]) {
    FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    size_t i;    
    if (nvr != 0 && (!value || !vr)) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                    fmi2Error, "error", "invalid memory access");
        return fmi2Error;
    }
    for (i = 0; i < nvr; i++) {
        if (vr[i] >= 0.0) {
            modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                    fmi2Error, "error", "valueReference out of range");
            return fmi2Error;
        }
    }
    for (i = 0; i < nvr; i++) {
        value[i] = (*modelData->bList[vr[i]] == false)?fmi2False:fmi2True;
        if (modelData->loggingOn) {
            modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
               fmi2OK, "info", "getBoolean vr:%d, value:%u", vr[i], value[i]);
        }
    }
    return fmi2OK;
}

fmi2Status fmi2SetBoolean(fmi2Component c, const fmi2ValueReference vr[], size_t nvr, const fmi2Boolean value[]) {
    FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    size_t i;    
    fmi2Boolean is_diff_value = fmi2False;
    if (nvr != 0 && (!value || !vr)) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                    fmi2Error, "error", "invalid memory access");
        return fmi2Error;
    }
    for (i = 0; i < nvr; i++) {
        if (vr[i] >= 0.0) {
            modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                    fmi2Error, "error", "valueReference out of range");
            return fmi2Error;
        }
    }
    for (i = 0; i < nvr; i++) {
        if (*modelData->bList[vr[i]] != ((value[i]==fmi2False)?false:true)) {
            is_diff_value = fmi2True;
            *modelData->bList[vr[i]] = (value[i]==fmi2False)?false:true;
        }
        if (modelData->loggingOn) {
            modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
               fmi2OK, "info", "setBoolean vr:%d, value:%u", vr[i], value[i]);
        }
    }
    return fmi2OK;
}

fmi2Status fmi2GetString (fmi2Component c, const fmi2ValueReference vr[], size_t nvr, fmi2String value[]) {
    FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    size_t i;    
    if (nvr != 0 && (!value || !vr)) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                    fmi2Error, "error", "invalid memory access");
        return fmi2Error;
    }
    for (i = 0; i < nvr; i++) {
        if (vr[i] >= 0.0) {
            modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                    fmi2Error, "error", "valueReference out of range");
            return fmi2Error;
        }
    }
    for (i = 0; i < nvr; i++) {
        value[i] = modelData->sList[vr[i]];
        if (modelData->loggingOn) {
            modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
               fmi2OK, "info", "getString vr:%d, value:%s", vr[i], value[i]);
        }
    }
    return fmi2OK;
}

fmi2Status fmi2SetString (fmi2Component c, const fmi2ValueReference vr[], size_t nvr, const fmi2String value[]) {
    FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    size_t i;    
    fmi2Boolean is_diff_value = fmi2False;
    size_t size;
    if (nvr != 0 && (!value || !vr)) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                    fmi2Error, "error", "invalid memory access");
        return fmi2Error;
    }
    for (i = 0; i < nvr; i++) {
       if (vr[i] >= 0.0) {
            modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                    fmi2Error, "error", "valueReference out of range");
            return fmi2Error;
        }
    }
    for (i = 0; i < nvr; i++) {
        if (strcmp(modelData->sList[vr[i]], value[i]) != 0) {
            is_diff_value = fmi2True;
            size = strlen(value[i]) < (modelData->sSize[vr[i]] - 1) ? strlen(value[i]) : (modelData->sSize[vr[i]] - 1);
            strncpy(modelData->sList[vr[i]], value[i], size);
            *((char*)modelData->sList[vr[i]]+size) = '\x00';
        }
        if (modelData->loggingOn) {
            modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
               fmi2OK, "info", "setString vr:%d, value:%s", vr[i], value[i]);
        }
    }
    return fmi2OK;
}

fmi2Status fmi2GetFMUstate(fmi2Component c, fmi2FMUstate* FMUstate) {
    FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    FMUInternalState* fmuInternalState = (FMUInternalState*)calloc(1, sizeof(FMUInternalState));
    memcpy(&fmuInternalState->ExternalInput, &Base_Model_three_drones_U, sizeof(ExtU_Base_Model_three_drones_T));
    memcpy(&fmuInternalState->ExternalOutput, &Base_Model_three_drones_Y, sizeof(ExtY_Base_Model_three_drones_T));
    memcpy(&fmuInternalState->Parameter, &Base_Model_three_drones_P, sizeof(P_Base_Model_three_drones_T));
    memcpy(&fmuInternalState->dWork, &Base_Model_three_drones_DW, sizeof(DW_Base_Model_three_drones_T));
    size_t i;
    for(i = 0; i < 86; i++) {
        fmuInternalState->rListBuffer[i] = *modelData->rList[i];
    }
    fmuInternalState->time = modelData->time;
    fmuInternalState->isNullInstance = (boolean_T)(_instance==NULL);
    if (modelData->loggingOn) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
           fmi2OK, "info", "FMUstate saved at time %f.", modelData->time);
    }
    *FMUstate = (void*)(fmuInternalState);
    return fmi2OK;
}

fmi2Status fmi2SetFMUstate(fmi2Component c, fmi2FMUstate FMUstate) {
    FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    FMUInternalState* fmuInternalState = (FMUInternalState*)FMUstate;
    if (!modelData->initialized) {
        MODEL_INITIALIZE();
        modelData->initialized = fmi2True;
    }
    if (modelData->loggingOn) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
           fmi2Warning, "info", "FMUstate contains opaque pointer that might cause unexpected simulation behavior.");
    }
    memcpy(&Base_Model_three_drones_U, &fmuInternalState->ExternalInput, sizeof(ExtU_Base_Model_three_drones_T));
    memcpy(&Base_Model_three_drones_Y, &fmuInternalState->ExternalOutput, sizeof(ExtY_Base_Model_three_drones_T));
    memcpy(&Base_Model_three_drones_P, &fmuInternalState->Parameter, sizeof(P_Base_Model_three_drones_T));
    memcpy(&Base_Model_three_drones_DW, &fmuInternalState->dWork, sizeof(DW_Base_Model_three_drones_T));
    size_t i;
    for(i = 0; i < 86; i++) {
         *modelData->rList[i] = fmuInternalState->rListBuffer[i];
    }
    if (modelData->loggingOn) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
           fmi2OK, "info", "FMUstate restored at time %f.", fmuInternalState->time);
    }
    modelData->time = fmuInternalState->time;
    _instance = (fmuInternalState->isNullInstance) ? NULL : modelData;
    return fmi2OK;
}

fmi2Status fmi2FreeFMUstate(fmi2Component c, fmi2FMUstate* FMUstate) {
    (void)c;
    FMUInternalState* fmuInternalState = (FMUInternalState*)*FMUstate;
    FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    (void)c;
    free(*FMUstate);
    return fmi2OK;
}

fmi2Status fmi2SerializedFMUstateSize(fmi2Component c, fmi2FMUstate FMUstate, size_t *size) {
    FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    if (!FMUstate) {
        *size = 0;
    }
   *size = sizeof(FMUInternalState);
    if (modelData->loggingOn) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
           fmi2OK, "info", "Serialized FMUState size: %d.", *size);
    }
   return fmi2OK;
}

fmi2Status fmi2SerializeFMUstate (fmi2Component c, fmi2FMUstate FMUstate, fmi2Byte serializedState[], size_t size) {
    FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    size_t copiedSize = sizeof(FMUInternalState);
    FMUInternalState* fmuInternalState = (FMUInternalState*)FMUstate;
    memcpy(serializedState, (fmi2Byte*)fmuInternalState, sizeof(FMUInternalState));
    if (modelData->loggingOn) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
           fmi2OK, "info", "fmi2SerializeFMUstate");
    }
    if (size != copiedSize) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, fmi2Error, "error",
                "fmi2SerializeFMUstate: invalid FMUState size %d of %d.", copiedSize, size);
        return fmi2Error;
    }
   return fmi2OK;
}

fmi2Status fmi2DeSerializeFMUstate (fmi2Component c, const fmi2Byte serializedState[], size_t size,
                                    fmi2FMUstate* FMUstate) {
    FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    size_t copiedSize = sizeof(FMUInternalState);
    if (!modelData->initialized) {
        MODEL_INITIALIZE();
        modelData->initialized = fmi2True;
    }
    FMUInternalState* fmuInternalState = (FMUInternalState*)calloc(1, sizeof(FMUInternalState));
    memcpy((char*)fmuInternalState, serializedState, sizeof(FMUInternalState));
    if (modelData->loggingOn) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
           fmi2OK, "info", "fmi2DeSerializeFMUstate");
    }
    if (size != copiedSize) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, fmi2Error, "error",
                "fmi2DeSerializeFMUstate: invalid FMUState size %d of %d.", copiedSize, size);
        return fmi2Error;
    }
    *FMUstate = fmuInternalState;
    return fmi2OK;
}

fmi2Status fmi2GetDirectionalDerivative(fmi2Component c, const fmi2ValueReference vUnknown_ref[], size_t nUnknown,
                                        const fmi2ValueReference vKnown_ref[] , size_t nKnown,
                                        const fmi2Real dvKnown[], fmi2Real dvUnknown[]) {
    (void)c;
    (void)vUnknown_ref;
    (void)nUnknown;
    (void)vKnown_ref;
    (void)nKnown;
    (void)dvKnown;
    (void)dvUnknown;
    return fmi2OK;
}

/* ---------------------------------------------------------------------------
 * Functions for FMI for Co-Simulation
 * ---------------------------------------------------------------------------
 */

/* Simulating the slave */
fmi2Status fmi2SetRealInputDerivatives(fmi2Component c, const fmi2ValueReference vr[], size_t nvr,
                                     const fmi2Integer order[], const fmi2Real value[]) {
    (void)c;
    (void)vr;
    (void)nvr;
    (void)order;
    (void)value;
    return fmi2OK;
}

fmi2Status fmi2GetRealOutputDerivatives(fmi2Component c, const fmi2ValueReference vr[], size_t nvr,
                                      const fmi2Integer order[], fmi2Real value[]) {
    size_t i;
    (void)c;
    (void)vr;
    (void)order;
    for (i = 0; i < nvr; i++) value[i] = 0;
    return fmi2OK;
}

fmi2Status fmi2CancelStep(fmi2Component c) {
    (void)c;
    return fmi2OK;
}

fmi2Status fmi2DoStep(fmi2Component c, fmi2Real currentCommunicationPoint,
                    fmi2Real communicationStepSize, fmi2Boolean noSetFMUStatePriorToCurrentPoint) {
    FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    int steps = 0;
    int i;
    fmi2Status returnStatus = fmi2OK;
    
    (void)noSetFMUStatePriorToCurrentPoint;
    steps = (int)(communicationStepSize / (double)0.01 + 0.5);    
    if (modelData->loggingOn) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
            fmi2OK, "info", "CommunicationStepSize=%.16g, LocalSolverStepSize=%.16g", communicationStepSize, (double)0.01);
    }
    if (communicationStepSize < 0 || fabs(communicationStepSize - steps * (double)0.01) > 1.0E-6 * (double)0.01) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                    fmi2Error, "error", "Stepsize must be non-negative and divisible by %.16g", (double)0.01);
        returnStatus = fmi2Error;
    } else if (fabs(modelData->time - currentCommunicationPoint) > 1.0E-6 * (double)0.01) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                    fmi2Error, "error", "CurrentCommunicationPoint is not equal to FMU time");
        returnStatus = fmi2Error;
    } else {
        modelData->time = currentCommunicationPoint;
        if (modelData->loggingOn) {
            modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                fmi2OK, "info", "Local solver will do %d steps from t = %.16g.", steps, currentCommunicationPoint);
        }
        for (i = 0; i < steps; i++) {
            if (rtmGetStopRequested(modelData->S)) {
                modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                        fmi2Error, "error", "stop requested in fmi2DoStep");
                returnStatus = fmi2Error;
                break;
            }
            rtOneStep(modelData->S);;
        }
        modelData->time += communicationStepSize;
    }
    
    if (modelData->functions->stepFinished) {
        modelData->functions->stepFinished(modelData->functions->componentEnvironment, returnStatus);
    }
    return returnStatus;
}

fmi2Status fmi2GetStatus(fmi2Component c, const fmi2StatusKind s, fmi2Status *value) {
    (void)c;
    (void)s;
    (void)value;
    return fmi2OK;
}

fmi2Status fmi2GetRealStatus(fmi2Component c, const fmi2StatusKind s, fmi2Real *value) {
    (void)c;
    (void)s;
    (void)value;
    return fmi2OK;
}

fmi2Status fmi2GetIntegerStatus(fmi2Component c, const fmi2StatusKind s, fmi2Integer *value) {
    (void)c;
    (void)s;
    (void)value;
    return fmi2OK;
}

fmi2Status fmi2GetBooleanStatus(fmi2Component c, const fmi2StatusKind s, fmi2Boolean *value) {
    (void)c;
    (void)s;
    (void)value;
    return fmi2OK;
}

fmi2Status fmi2GetStringStatus(fmi2Component c, const fmi2StatusKind s, fmi2String *value) {
    (void)c;
    (void)s;
    (void)value;
    return fmi2OK;
}

/* ---------------------------------------------------------------------------
 * Functions for FMI for Model Exchange
 * ---------------------------------------------------------------------------
 */

fmi2Status fmi2CompletedIntegratorStep(fmi2Component c, fmi2Boolean noSetFMUStatePriorToCurrentPoint, fmi2Boolean* enterEventMode, fmi2Boolean* terminateSimulation) {
    (void)c;
    (void)noSetFMUStatePriorToCurrentPoint;
    (void)enterEventMode;
    (void)terminateSimulation;
    return fmi2OK;
}

fmi2Status fmi2EnterContinuousTimeMode(fmi2Component c) {
    (void)c;
    return fmi2OK;
}

fmi2Status fmi2EnterEventMode(fmi2Component c) {
    (void)c;
    return fmi2OK;
}

fmi2Status fmi2GetContinuousStates(fmi2Component c, fmi2Real x[], size_t nx) {
    (void)c;
    (void)x;
    (void)nx;
    return fmi2OK;
}

fmi2Status fmi2GetDerivatives(fmi2Component c, fmi2Real derivatives[], size_t nx) {
    (void)c;
    (void)derivatives;
    (void)nx;
    return fmi2OK;
}

fmi2Status fmi2GetEventIndicators(fmi2Component c, fmi2Real eventIndicators[], size_t ni) {
    (void)c;
    (void)ni;
    (void)eventIndicators;
    return fmi2OK;
}

fmi2Status fmi2GetNominalsOfContinuousStates(fmi2Component c, fmi2Real x_nominal[], size_t nx) {
    (void)c;
    (void)x_nominal;
    (void)nx;
    return fmi2OK;
}

fmi2Status fmi2NewDiscreteStates(fmi2Component c, fmi2EventInfo* fmi2eventInfo) {
    (void)c;
    (void)fmi2eventInfo;
    return fmi2OK;
}

fmi2Status fmi2SetContinuousStates(fmi2Component c, const fmi2Real x[], size_t nx) {
    (void)c;
    (void)x;
    (void)nx;
    return fmi2OK;
}

fmi2Status fmi2SetTime(fmi2Component c, fmi2Real time) {
    (void)c;
    (void)time;
    return fmi2OK;
}
